// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddUserData, AddUserResponses, DeleteUserData, DeleteUserResponses, GetLoginUserData, GetLoginUserResponses, GetUserByIdData, GetUserByIdResponses, GetUserVoByIdData, GetUserVoByIdResponses, UpdateMyUserData, UpdateMyUserResponses, UpdateUserData, UpdateUserResponses, UserLoginData, UserLoginResponses, UserLogoutData, UserLogoutResponses, UserRegisterData, UserRegisterResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const updateUser = <ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>) => (options.client ?? client).post<UpdateUserResponses, unknown, ThrowOnError>({
    url: '/user/update',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const updateMyUser = <ThrowOnError extends boolean = false>(options: Options<UpdateMyUserData, ThrowOnError>) => (options.client ?? client).post<UpdateMyUserResponses, unknown, ThrowOnError>({
    url: '/user/update/my',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const userRegister = <ThrowOnError extends boolean = false>(options: Options<UserRegisterData, ThrowOnError>) => (options.client ?? client).post<UserRegisterResponses, unknown, ThrowOnError>({
    url: '/user/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const userLogout = <ThrowOnError extends boolean = false>(options?: Options<UserLogoutData, ThrowOnError>) => (options?.client ?? client).post<UserLogoutResponses, unknown, ThrowOnError>({ url: '/user/logout', ...options });

export const userLogin = <ThrowOnError extends boolean = false>(options: Options<UserLoginData, ThrowOnError>) => (options.client ?? client).post<UserLoginResponses, unknown, ThrowOnError>({
    url: '/user/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>) => (options.client ?? client).post<DeleteUserResponses, unknown, ThrowOnError>({
    url: '/user/delete',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const addUser = <ThrowOnError extends boolean = false>(options: Options<AddUserData, ThrowOnError>) => (options.client ?? client).post<AddUserResponses, unknown, ThrowOnError>({
    url: '/user/add',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getUserById = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdData, ThrowOnError>) => (options.client ?? client).get<GetUserByIdResponses, unknown, ThrowOnError>({ url: '/user/get', ...options });

export const getUserVoById = <ThrowOnError extends boolean = false>(options: Options<GetUserVoByIdData, ThrowOnError>) => (options.client ?? client).get<GetUserVoByIdResponses, unknown, ThrowOnError>({ url: '/user/get/vo', ...options });

export const getLoginUser = <ThrowOnError extends boolean = false>(options?: Options<GetLoginUserData, ThrowOnError>) => (options?.client ?? client).get<GetLoginUserResponses, unknown, ThrowOnError>({ url: '/user/get/login', ...options });
