// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/api' | (string & {});
};

export type UserUpdateRequest = {
    id?: number;
    userName?: string;
    userAvatar?: string;
    userProfile?: string;
    userRole?: string;
};

export type BaseResponseBoolean = {
    code?: number;
    data?: boolean;
    message?: string;
};

export type UserUpdateMyRequest = {
    userName?: string;
    userAvatar?: string;
    userProfile?: string;
};

export type UserRegisterRequest = {
    userAccount?: string;
    userPassword?: string;
    checkPassword?: string;
};

export type BaseResponseLong = {
    code?: number;
    data?: number;
    message?: string;
};

export type UserLoginRequest = {
    userAccount?: string;
    userPassword?: string;
};

export type BaseResponseLoginUserVo = {
    code: number;
    data: LoginUserVo;
    message?: string;
};

export type LoginUserVo = {
    id?: number;
    username?: string;
    avatarUrl?: string;
    userAccount?: string;
    gender?: number;
    email?: string;
    phone?: string;
    userRole?: string;
    createTime?: string;
    updateTime?: string;
};

export type DeleteRequest = {
    id?: number;
};

export type BaseResponseString = {
    code?: number;
    data?: string;
    message?: string;
};

export type UserAddRequest = {
    userName?: string;
    userAccount?: string;
    userAvatar?: string;
    userRole?: string;
};

export type BaseResponseUser = {
    code?: number;
    data?: User;
    message?: string;
};

export type User = {
    id?: number;
    username?: string;
    userAccount?: string;
    email?: string;
    userPassword?: string;
    phone?: string;
    createTime?: string;
    updateTime?: string;
    avatarUrl?: string;
    gender?: number;
    balance?: number;
    isDelete?: number;
    userRole?: number;
};

export type BaseResponseUserVo = {
    code?: number;
    data?: UserVo;
    message?: string;
};

export type UserVo = {
    id?: number;
    userName?: string;
    userAvatar?: string;
    userProfile?: string;
    userRole?: string;
    createTime?: string;
    balance?: number;
};

export type UpdateUserData = {
    body: UserUpdateRequest;
    path?: never;
    query?: never;
    url: '/user/update';
};

export type UpdateUserResponses = {
    /**
     * OK
     */
    200: BaseResponseBoolean;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type UpdateMyUserData = {
    body: UserUpdateMyRequest;
    path?: never;
    query?: never;
    url: '/user/update/my';
};

export type UpdateMyUserResponses = {
    /**
     * OK
     */
    200: BaseResponseBoolean;
};

export type UpdateMyUserResponse = UpdateMyUserResponses[keyof UpdateMyUserResponses];

export type UserRegisterData = {
    body: UserRegisterRequest;
    path?: never;
    query?: never;
    url: '/user/register';
};

export type UserRegisterResponses = {
    /**
     * OK
     */
    200: BaseResponseLong;
};

export type UserRegisterResponse = UserRegisterResponses[keyof UserRegisterResponses];

export type UserLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/logout';
};

export type UserLogoutResponses = {
    /**
     * OK
     */
    200: BaseResponseBoolean;
};

export type UserLogoutResponse = UserLogoutResponses[keyof UserLogoutResponses];

export type UserLoginData = {
    body: UserLoginRequest;
    path?: never;
    query?: never;
    url: '/user/login';
};

export type UserLoginResponses = {
    /**
     * OK
     */
    200: BaseResponseLoginUserVo;
};

export type UserLoginResponse = UserLoginResponses[keyof UserLoginResponses];

export type DeleteUserData = {
    body: DeleteRequest;
    path?: never;
    query?: never;
    url: '/user/delete';
};

export type DeleteUserResponses = {
    /**
     * OK
     */
    200: BaseResponseBoolean;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type UploadAvatarData = {
    body?: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/user/avatar';
};

export type UploadAvatarResponses = {
    /**
     * OK
     */
    200: BaseResponseString;
};

export type UploadAvatarResponse = UploadAvatarResponses[keyof UploadAvatarResponses];

export type AddUserData = {
    body: UserAddRequest;
    path?: never;
    query?: never;
    url: '/user/add';
};

export type AddUserResponses = {
    /**
     * OK
     */
    200: BaseResponseLong;
};

export type AddUserResponse = AddUserResponses[keyof AddUserResponses];

export type GetUserByIdData = {
    body?: never;
    path?: never;
    query: {
        id: number;
    };
    url: '/user/get';
};

export type GetUserByIdResponses = {
    /**
     * OK
     */
    200: BaseResponseUser;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type GetUserVoByIdData = {
    body?: never;
    path?: never;
    query: {
        id: number;
    };
    url: '/user/get/vo';
};

export type GetUserVoByIdResponses = {
    /**
     * OK
     */
    200: BaseResponseUserVo;
};

export type GetUserVoByIdResponse = GetUserVoByIdResponses[keyof GetUserVoByIdResponses];

export type GetLoginUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/get/login';
};

export type GetLoginUserResponses = {
    /**
     * OK
     */
    200: BaseResponseLoginUserVo;
};

export type GetLoginUserResponse = GetLoginUserResponses[keyof GetLoginUserResponses];
